import tarski.main.*, Sizes.*, Shape.*, Tone.*

val WittgensteinWorld: Grid = Map(
  (0, 1) -> Block(Large, Squ, Blue, "d"),
  (0, 4) -> Block(Large, Cir, Green, "e"),
  (0, 7) -> Block(Large, Tri, Gray, "f"),
  (4, 0) -> Block(Mid, Tri, Blue),
  (4, 3) -> Block(Mid, Squ, Green, "c"),
  (4, 6) -> Block(Mid, Cir, Gray),
  (6, 1) -> Block(Small, Tri, Green, "a"),
  (6, 4) -> Block(Small, Squ, Gray, "b"),
  (6, 7) -> Block(Small, Cir, Blue)
)

val WittgenSteinSentences = Seq(
  fof"Large(d)",
  fof"Large(c)",
  fof"Large(f)",
  fof"Mid(c)",
  fof"Mid(b)",
  fof"Mid(f)",
  fof"Larger(c, b)",
  fof"Larger(d, e)",
  fof"Larger(d, f)",
  fof"Larger(a, e)",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof"",
  fof""
)

@main
def run01 = runWorld(WittgensteinWorld, WittgenSteinSentences)
